### ISSUE TITLE
Bug with portrait images and landscape aspect ratio

### ISSUE THREAD

**Issue by SergeShkurko** [xclud/flutter_crop#1]
![image](https://user-images.githubusercontent.com/18213789/73119743-7718e600-3f77-11ea-920a-8583788f24c5.png)
It seems to me that it would be necessary to enlarge the image so that it does not go beyond

**Comment by xclud** [comment]
Did you update the 'aspectRatio' property of the Crop widget?

Can you please paste some code here?

**Comment by SergeShkurko** [comment]
@xclud i run example from repository and replace landscape image by portrait image https://github.com/xclud/flutter_crop/blob/master/example/lib/main.dart#L69

![sample_vertical](https://user-images.githubusercontent.com/18213789/73119863-c01d6a00-3f78-11ea-96a4-72af0ce0bef7.jpg)

**Comment by xclud** [comment]
I will investigate the issue and will fix. Thanks for reporting.

**Comment by SergeShkurko** [comment]
Thanks

**Comment by tapeo** [comment]
Same problem! Hope for a fix soon! If you need help tell me :)

**Comment by xclud** [comment]
@tapeo i am aware of this issue. Hopefully i will fix it this weekend. Feel free to contribute!

**Comment by xclud** [comment]
This bug is fixed now. please update to v0.2.1 to get the latest bits.

I am closing this issue but please feel free to open new issues.
