### ISSUE TITLE
Remove print statement when panning image around

### ISSUE THREAD

**Issue by Pomb** [xclud/flutter_crop#12]
Using the cropper it's flooding the terminal window with print statements.

**Comment by xclud** [comment]
Hi @Pomb, this is already fixed in #9. Did you update to version `0.3.1+1`?

In `pubspec.yaml` if you are referencing the package using `crop: any` you must run `flutter pub upgrade` **in your project directory** to update the package reference.

Please tell me if this fixes the problem.

**Comment by xclud** [comment]
I am closing this issue as you didn't response and i assume this is fixed by now.

**Comment by Pomb** [comment]
Appologies, @xclud. Yes thank you it's fixed.
