### ISSUE TITLE
Save Image to temporal directory?

### ISSUE THREAD

**Issue by fenchai23** [xclud/flutter_crop#14]
I know you provided a way to save image to "gallery" and this function returns a strange path?

```Dart
Future<dynamic> _saveScreenShot(ui.Image img) async {
    var byteData = await img.toByteData(format: ui.ImageByteFormat.png);
    var buffer = byteData.buffer.asUint8List();
    final result = await ImageGallerySaver.saveImage(buffer);
    print(result);

    return result;
  }
```

this path is pretty weird as I can't reference it.
`file:///storage/emulated/0/H%20Y%20L/1588915650844.png`
If I do `File(imgPath)` The file is invalid, well file can't be loaded or opened, etc.

is there a way to save it into `getTemporaryDirectory()` and give it a fixed named?

**Comment by xclud** [comment]
@fenchai23 Do you get an error message in console? It could be the problem with permission to access files.

btw, take a look at this gist: https://gist.github.com/zgramming/e4717686aef543fb690fbe481b81cc61

Let me know.

**Comment by fenchai23** [comment]
it's not permission because I already gave my app storage permission, also there are no errors while running the `_saveScreenShot()` method.

the result is `file:///storage/emulated/0/H%20Y%20L/1588950933361.png` and the picture is indeed created but the correct path should be `file:///storage/emulated/0/HYL/1588950933361.png` ? or maybe `/storage/emulated/0/HYL/1588950933361.png` ?

I went into the file properties and this is the URI `content://com.android.externalstorage.documents/document/primary%3AH%20Y%20L%2F1588915152922.png`

but It would be nice to be able to save it into a custom path? this way there is no need to use storage permissions and I can save it into a different more static name.

**Comment by xclud** [comment]
Did you try the gist i posted above? If it's not working i will update the example app for you, but it will take a while.

**Comment by fenchai23** [comment]
I did try to tinker it a bit and will still be trying...

```Dart
Future<dynamic> _saveScreenShot(ui.Image img) async {
    var byteData = await img.toByteData(format: ui.ImageByteFormat.png);
    var buffer = byteData.buffer.asUint8List();
    
    final File imagePath = File(join(
      (await getTemporaryDirectory()).path, //Temporary path
      'pic_${DateTime.now()}.png'),
    );

    imagePath.writeAsStringSync(buffer);

    // final result = await ImageGallerySaver.saveImage(buffer);
    // print(result);

    return imagePath.path;
  }
```

But buffer is not String so I'm gonna have to find a way to convert it I think.

**Comment by fenchai23** [comment]
yup, the above function worked :) 

btw offtopic here, but is there no way to freeform change the cropping size? and we are stuck on using ratios? it seems most cropping packages are limited to ratio size. It seems
