### ISSUE TITLE
How to specify the dimensions of the area of the cropped image?

### ISSUE THREAD

**Issue by mlemos** [xclud/flutter_crop#16]
Is it possible to make the cropped area of a specific width and height?

**Comment by xclud** [comment]
@mlemos It works by setting aspect ratio which is width/height. Once you crop with desired ratio, you can resize the image using (e.g. using another package) to desired dimentions. Does this work for you?

**Comment by mlemos** [comment]
Hi @xclud , thanks for the explanation.

I got the aspect ratio, but it is not what I need. My goal was to have some padding around the area that will be cropped. But it is impossible since it will be occupying the full width or height depending on the aspect ratio.

**Comment by xclud** [comment]
@mlemos Can't you just zoom in ?

**Comment by xclud** [comment]
I close this issue as it is inactive for a while now. Please feel free to open a new issue any time.
