### ISSUE TITLE
Circle crop preview

### ISSUE THREAD

**Issue by Pomb** [xclud/flutter_crop#18]
Would be really nice to specify the preview shape of the clipper that controls the dim background.
Something like: `clipper: Clippers.Oval` or `clipper: Clippers.Box`
I've been adding a second widget as an overlay and setting the dim color to transparent as a work around.

**Comment by xclud** [comment]
This is a great suggestion. We will track the idea here :)

**Comment by QuentinSc** [comment]
When it's done I switch on your package ! awesome work

**Comment by xclud** [comment]
@QuentinSc thank you for the feedback. This helps me prioritize the features.

**Comment by xclud** [comment]
@songfei Thank you for the PR #20. This is a great addition to the package.

**Comment by xclud** [comment]
This issue is fixed now thanks to @songfei. Closing.

**Comment by xclud** [comment]
Fixed in version 0.4.0.
