### ISSUE TITLE
The cropped image's quality needs to be improved.

### ISSUE THREAD

**Issue by idootop** [xclud/flutter_crop#2]
![Snipaste_2020-02-07_14-38-37](https://user-images.githubusercontent.com/35302658/74006971-27dfa600-49b8-11ea-8df9-d51b73fac537.png)
recommend to add a pixelRatio api to adjust the cropped image's quality.

**Comment by xclud** [comment]
Yes, I recently noticed about the quality degrade.

But `window` is a web-only API. Isn't it?

**Comment by xclud** [comment]
This is fixed by passing `pixelRatio` to crop function.

See https://github.com/xclud/flutter_crop/commit/39b3d9dbb572d64fc93b46520240b454b1f54c81

**Comment by xclud** [comment]
I am closing this issue. Please feel free to reopen or open a new issue.

**Comment by idootop** [comment]
> 
> 
> I am closing this issue. Please feel free to reopen or open a new issue.

Cool. Thanks!
