### ISSUE TITLE
Unexpected behavior when cropping

### ISSUE THREAD

**Issue by ekleel** [xclud/flutter_crop#21]
First thank you for this simple and great package, we've been looking for a package that's easy to customize and supports desktop and web.

While I was implementing the crop functionality I noticed a strange behavior and I don't think it was designed to be used in this way. I't not easy to explain so I've posted a video to show the problem. In short, the crop area does not include the parts of the image that are not within the provided aspect ratio. For example, when setting the aspect ratio to `1.0`, you can't move the image outside the square. You can however rotate or scale this area.

[Example Video](https://youtu.be/_P8ChpUHew0)

I've tested this on a physical Android device using the app on Google Play. I've also tested it on macOS using latest versions of Flutter and flutter_crop `[0.4.0]`.

Doctor:
```
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale en-SA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)

• No issues found!
```

Thanks again.

**Comment by ekleel** [comment]
Apparently this is caused by `fit: BoxFit.cover`. Is there a workaround to allow moving the full image inside the crop area?
```
Crop(
  controller: widget.cropController,
  helper: Container(
    decoration: BoxDecoration(
      border: Border.all(
        color: Colors.white,
        width: 2.0,
      ),
    ),
  ),
  child: Image(
    image: widget.imageProvider,
    fit: BoxFit.cover,
  ),
)
```

**Comment by xclud** [comment]
@ekleel fit: BoxFit.cover is to make sure the image inside the area is not smaller or bigger than the area so it never leaves empty space or exceed the screen.

Did you resolve the problem now or you still need help ?
