### ISSUE TITLE
6,8 edge crop

### ISSUE THREAD

**Issue by anirudh-t4** [xclud/flutter_crop#35]
I am extensively using this package and i need a 6 or 8 edge cropping instead of the 4.
Kindly help

**Comment by xclud** [comment]
Hi @anirudh-t4,
Supporting custom paddings is on the roadmap of the package. I hope i will get some free time to implement this.

**Comment by anirudh-t4** [comment]
Thanks for your reply.
I'd be very grateful if you can implement the 6,8 edge crop or share some
idea about how can i implement it
Regards
Anirudh

**Comment by anirudh-t4** [comment]
Hey sir,
I am in tremendous need of a 6,8 edge cropper for my project.
Can you share some idea of how to implement it in dart or until when can i expect it in your package.

**Comment by xclud** [comment]
Currently there is no ETA on this feature. I believe you can modify the source code to achieve this. It's not hard. I made the package as simple as possible.

**Comment by anirudh-t4** [comment]
Can you give some suggestions as to where i should make these changes?
I just want the 4 edges to become 8
