### ISSUE TITLE
multiple crop instances on same page

### ISSUE THREAD

**Issue by W34therwax** [xclud/flutter_crop#37]
Hello! 

Thanks for such a great package, working great so far. 

I have though an issue with implementing multiple crop images on one view. I have three thumbnails, clicking on each display bigger image that can be cropped. I am creating three separate instances CropController and Crop widget, and switching between them. 

Issue is, when user adjust picture, zoom it and drag somewhere. This works, but after switching to another image (so changing CropController and Crop widget), and then changing back to our modified picture image is zoomed as it was done by user, but its always **centered**, so drag part is forgotten. But! it's not really forgotten, as if user tap the screen, image jump immediately to that place where drag was done on the first place. Flow is on attached gif.

Do you have any idea how could I restore user "drag" position when switching images? Thanks in advance!

issue
![issue](https://user-images.githubusercontent.com/51397668/98530139-d33ac580-227e-11eb-924f-5c16e197e250.gif)

 
![Zrzut ekranu 2020-11-9 o 11 02 41](https://user-images.githubusercontent.com/51397668/98527270-1a26bc00-227b-11eb-95f7-bfa84e1c24b3.png)

**Comment by xclud** [comment]
Hi @W34therwax,
Can you give a working project so i can investigate further? Sending a link to your repository or attaching a zip file is enough.

**Comment by W34therwax** [comment]
Hey @xclud , I have extracted those parts from my project and put it in your example project. Compressing it took a lot of space, big zip file, so what I did is put here two zips - one is lib directory and another pubspec file. If you replace that in your example project, install dependencies it will work. For first time I run that it did not worked, but after closing and reopening its fine. I can reproduce my issue there as on my original project.

Only one requirement, on your device/emulator you need to have images (at least 3) in your gallery. Please let me know if I can help in any other way.

[lib.zip](https://github.com/xclud/flutter_crop/files/5510049/lib.zip)
[pubspec.yaml.zip](https://github.com/xclud/flutter_crop/files/5510052/pubspec.yaml.zip)

**Comment by W34therwax** [comment]
Hey @xclud, any luck with figuring this out? I have tried my best, but no success so far :/. Maybe it would help if I trim that example more from some unnecessary code?

**Comment by xclud** [comment]
@W34therwax, I didn't get free time to investigate the problem. I will check your code on the weekends and will let you know.

**Comment by W34therwax** [comment]
@xclud hello again! Did you maybe have some time for that? Actually maybe you have some different approach/idea how to attempt cropping more than one image on one view?

**Comment by xclud** [comment]
Sorry for my late reply. I've attached a working example for you.
[multi_crop.zip](https://github.com/xclud/flutter_crop/files/5624315/multi_crop.zip)
