### ISSUE TITLE
How to achieve the instagram crop functionality?

### ISSUE THREAD

**Issue by Wizzel1** [xclud/flutter_crop#40]
Hi, first of all, I wanted to thank you for this awesome package!

I am trying to recreate the cropping from Instagram and I am a bit lost, to be honest.

This is my current screen:
![1](https://user-images.githubusercontent.com/43343510/98976938-44e17080-2518-11eb-9aad-0df8802d5f40.JPG)

Currently, the aspect ratio is set to 9/16 but this obviously isn't what I need.

The screen currently looks like this: 

```
Scaffold(
   body: Column( 
       Crop(),
       GridView(),
    )
)
```

My questions are:

1) How do I determine the correct aspect ratio to get boundaries like the Instagram cropper? 
2) How would I implement the button that sets the size of the media to full width? 

Edit: I would also need to reset the x value of Offset to 0 after an element is dragged.  Is there an easy way to do it or do I have to fork the package to do that?

Thanks!

**Comment by xclud** [comment]
Hi @Wizzel1 tahnk you for using crop. I will reach to you soon. Sorry for replying late.
