### ISSUE TITLE
How to crop the original image.

### ISSUE THREAD

**Issue by HeebeLee** [xclud/flutter_crop#41]
I refer to the demo code. After loading an image, the image will be automatically cropped to a scale. But I don't want to do this, I want to be able to slide through the original image, zoom in and out, and so on.

Can it be realized? This function is urgently needed.

**Comment by HeebeLee** [comment]
@xclud Maybe we focus on one location instead of cutting it into a picture.
This is very important to me and I hope it can be provided.

**Comment by xclud** [comment]
Can you please describe the problem with more details? Possibly with a pic/video showing the problem.

**Comment by HeebeLee** [comment]
Just like #27 , we all want to do it at the same size.

Should this be initialized when, instead of clipping, the cardinality should be enlarged?

**Comment by nwparker** [comment]
@HeebeLee I propose you close this issue and move conversation into #27 

I've just posted a video there demonstrating the issue

**Comment by xclud** [comment]
@HeebeLee @nwparker  I am closing this issue. Please follow the conversation about this issue in #27.
