### ISSUE TITLE
Crop issues under Flutter web (Android is fine)

### ISSUE THREAD

**Issue by pulstar** [xclud/flutter_crop#42]
1) How do I zoom in/out in Flutter web?

2) Why do the crop window always return to the image's center after I try to pan it?

3) I compiled the crop demo, but the image inside the crop window is very dark (see below). The online demo is working fine.

![image](https://user-images.githubusercontent.com/1308392/100276009-9ee22d00-2f3f-11eb-9b73-bbd1584494fc.png)

4) The oval shape does not show in Flutter web.

**Comment by xclud** [comment]
@pulstar you must set `FLUTTER_WEB_USE_SKIA` to `true`. Here is how you compile for web:

`flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true`

Let me know if this works for you.

**Comment by pulstar** [comment]
I run the above command but it didn't open any window and ended silently... 
So I added the parameter to the run configurations and it worked. 
Will it also work when I build the app?

Well, the items 3 and 4 are okay, what about the items 1 and 2?

**Comment by xclud** [comment]
- For 1: On a touch-screen (mobile) you can use two fingers to zoom in. on desktop i guess it's not possible. It's a good point though. I will implement this functionality. For the moment a zoom slider comes handy.

- For 2: You may not go off-canvas. It has to fill the canvas area with the image.

For 3 and 4: I am happy it worked for you.

**Comment by pulstar** [comment]
1) A zoom slider will be nice! :-)

2) I made some tests, but it always goes to the center, despite it is on-canvas. On Android it works fine.

**Comment by xclud** [comment]
Do you get the wrong behavior on my web-demo as well? If yes:

- Would you please attach a video/gif?
- Would you paste the output of `flutter doctor -v` here.

**Comment by pulstar** [comment]
Since I cannot zoom in, probably it is one pixel or two off-canvas when I pan the image to the right or left. 
Your web-demo have also the same behavior. I am using Google Chrome for my tests.

```
[√] Flutter (Channel dev, 1.24.0-3.0.pre, on Microsoft Windows [version 10.0.18363.1198], locale pt-BR)
    • Flutter version 1.24.0-3.0.pre at C:\src\flutter
    • Framework revision 2783f8e2e1 (5 weeks ago), 2020-10-22 09:36:06 -0700
    • Engine revision defa8be2b1
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • Vivo XI (mobile)  • PRUCHYWGG6HYSK4H • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [version 10.0.18363.1198]
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 87.0.664.47

! Doctor found issues in 1 category.
```

**Comment by xclud** [comment]
Usually if you rotate the image (with slider) it will zoom and there will be a little room for panning. Do you get this behavior?

**Comment by pulstar** [comment]
Yes, I did try that too at various angles, but no success.

**Comment by xclud** [comment]
Can you please attach a video/gif?

**Comment by pulstar** [comment]
See it at:  https://youtu.be/Kvz0nYK9e4o

**Comment by pulstar** [comment]
Before trying your plug-in, I tried another web-compatible package, but it has serious problems and the author does not answer here on Github. As you expressed concern, I will choose your plug-in, which is even better.

**Comment by xclud** [comment]
Sorry for my late answer. I've watched your video. We are already discussing this problem on #27.

If you think it's better, please closing this issue and track the other one.

And thank you for choosing my package.

**Comment by pulstar** [comment]
Okay
