### ISSUE TITLE
2 things: 1) reposition photo 2) zoom

### ISSUE THREAD

**Issue by bartonhammond** [xclud/flutter_crop#45]
Great job!

I'd like to move my image up/down and I'd like to zoom in/out

Thanks for doing this!

**Comment by xclud** [comment]
Thank you @bartonhammond for your support.

Is there any issue or question i can help? Shall i close the issue?

**Comment by bartonhammond** [comment]
Is this something you'll do?  I haven't seen how to reposition the image.  My photos always have the top part of the head chopped on.  And I haven't seen a way to zoom.  Are these things supported?  If not, would you consider?

**Comment by xclud** [comment]
This is a known bug in the package. We are already discussing this in #27.

**Comment by bartonhammond** [comment]
Ok - Great
