### ISSUE TITLE
Dimm color cover all widget (not only the outer part of the image) [web - 1.24.0-10.2.pre]

### ISSUE THREAD

**Issue by JoaquinNievas** [xclud/flutter_crop#49]
The entire image to be cropped is dimmed. I thought it was a problem with my code, but I downloaded your sample project and ran it in Chrome, and the same thing happened. My Flutter version is 1.24.0-10.2.pre Beta

<img width="1201" alt="crop error" src="https://user-images.githubusercontent.com/58852652/106189391-035f7980-6187-11eb-9c5b-90863063e078.png">

**Comment by xclud** [comment]
Hi. You should compile with Skia enabled:

`flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true`

The flag `FLUTTER_WEB_USE_SKIA` is important. Please let me know if this solves the problem.

**Comment by kiaxseventh** [comment]
hi.
tried with   flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true  flag and it has the same issue


my Flutter version is 1.27.0-2.0.pre.126

**Comment by xclud** [comment]
@kiaxseventh Can you confirm if this happens on desktop mode as well?

**Comment by kiaxseventh** [comment]
@xclud
 hello again
 i changed my flutter  sdk to 1.25.0-8.2.pre beta channel with FLUTTER_WEB_USE_SKIA flag build everything is good
i tried it with android (chrome) and ios (safari) and windows(chrome) its ok and dont have any problem

**Comment by xclud** [comment]
@kiaxseventh Good to hear that. I am closing this issue but feel free to open a new issue any time.

**Comment by kiaxseventh** [comment]
hello again 
i changed my flutter sdk to 2.0.4 stable it have problem again !
on  desktop web dont has any problem
but on mobile chrome it has problme 
are you have solution ?

**Comment by kiaxseventh** [comment]
i tried  again with this command everything  is ok 

` flutter build web --web-renderer canvaskit --release
`

**Comment by xclud** [comment]
@kiaxseventh Are you passing the `FLUTTER_WEB_USE_SKIA` flag?

**Comment by kiaxseventh** [comment]
> @kiaxseventh Are you passing the `FLUTTER_WEB_USE_SKIA` flag?

no
add full command example please

**Comment by xclud** [comment]
`flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true`

**Comment by kiaxseventh** [comment]
> `flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true`

yes i tried it my problem fixed with this command 

`flutter build web --web-renderer canvaskit --release
`

**Comment by xclud** [comment]
Nice to hear that.

**Comment by vanshg395** [comment]
I want this to work in this config as well. Will that be possible?

`flutter build web --web-renderer html --release`

**Comment by xclud** [comment]
@vanshg395 Shape-clipping is not implemented in html backend. It seems flutter team is not developing html backend anymore and eventually flutter will switch to Skia. Not possible.
