### ISSUE TITLE
Aspect ratio from within the image boundaries.

### ISSUE THREAD

**Issue by pkitatta** [xclud/flutter_crop#5]
Hi, great little plugin. I am trying to use it to help users of an app upload their avatar. The avatar has to be square in shape. Is it possible to ensure that the user can't pinch the image below the square aspect ratio just like in the photo below - borrowing @SergeShkurko photo. 

![2020-03-03_15h52_34](https://user-images.githubusercontent.com/17586059/75777837-c4068e00-5d67-11ea-9bd9-b2f58d84a426.png)

Thanks.

**Comment by xclud** [comment]
Hi @pkitatta do you mean if the crop area is out of image and it's empty/blank? This should not happen already. If you have this problem probably you've found a big. Could you share more details?

PS: currently there is a bug if the crop aspectratio does not match with the image aspectratio, which i am aware of and working on a fix.

**Comment by pkitatta** [comment]
> Hi @pkitatta do you mean if the crop area is out of image and it's empty/blank? This should not happen already. If you have this problem probably you've found a big. Could you share more details?
> 
> PS: currently there is a bug if the crop aspectratio does not match with the image aspectratio, which i am aware of and working on a fix.

Maybe it's this. My challenge is the extra space that is not an image again using @SergeShkurko's photo for convenience (but imagine it's a 1:1 ratio):

![2020-03-03_16h21_09](https://user-images.githubusercontent.com/17586059/75780100-d97db700-5d6b-11ea-994f-25bbf7dee1a3.png)

The default position of the cropper should always remain in the confines of the image boundary.

If it's a similar issue you are aware of then it's ok. We shall wait to the fix.

**Comment by xclud** [comment]
Yes it is the same issue. I appreciate your wait. Meanwhile can you please test if the problem exists if the widget aspect ratio is the same is the image aspect ratio?

**Comment by pkitatta** [comment]
OK. Will let you know.

**Comment by pkitatta** [comment]
OK so a square image does work well in the 1:1 aspect ratio I have defined.

**Comment by xclud** [comment]
Thank you for the feedback. Please keep using the package without worrying about this bug. A fix will arrive soon. And please dont hesitate posting issues or contributing.

**Comment by xclud** [comment]
@pkitatta this bug is now fixed in v0.2.1.

**Comment by pkitatta** [comment]
Thanks will try again.
