### ISSUE TITLE
Image.network() support?

### ISSUE THREAD

**Issue by willladislaw** [xclud/flutter_crop#51]
I'm getting an error for `Image.network('..')`

The cause of this appears to be  `--web-renderer auto` (flutter run  --web-renderer auto)

Removing the flag and just using `flutter run` resolves above but now gives `Error: Unsupported operation: toImage is not supported on the Web` when "crop" button is clicked from the example. 

```
Crop(
                controller: controller,
                shape: shape,
                child: Image.network(
                  'https://example.com/f8133f38f44.png',
                  fit: BoxFit.cover,
                ),
...
)
```
Error:

Image provider:
  NetworkImage("https://example.com/f8133f38f44.png",
  scale: 1)
Image key:
  NetworkImage("https://example.com/f8133f38f44.png",
  scale: 1)

flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/me/flutter
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 53.0.1
    • Dart plugin version 201.7223.99

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!

**Comment by xclud** [comment]
Hi @willladislaw

Flutter's built-in `Scene` has implemented `toImage` method only on Skia. So it will not work on `DOM`. Setting the renderer to `auto` will cause the renderer to switch between Skia and DOM. That's why.
