### ISSUE TITLE
Cut in the top position

### ISSUE THREAD

**Issue by brnostone** [xclud/flutter_crop#59]
Apparently there is a bug that does not allow me to select an upper or lower part of the initial cut. I'm using the sample code.
As you can see in the video, I can't cut in the red or green circle, only yellow. Do you have a solution or is it a bug?

[demo.zip](https://github.com/xclud/flutter_crop/files/6346981/demo.zip)

**Comment by xclud** [comment]
Hi @brnostone 

This is a dup of #27. I am actively working on this bug.

I close this issue. Feel free to join the conversation in #27 or open a new issue any time.
