### ISSUE TITLE
Rotation by 180 degrees does not work

### ISSUE THREAD

**Issue by micdoug** [xclud/flutter_crop#6]
I have been playing with the library and I found an issue when trying to rotate images by 180 degrees or higher. It seems that the library is not handling it correctly. When I try to rotate by 180, the image is placed with 0 rotation (the original position).  I tried to debug the code, but I don't have enough knowledge of image manipulation algorithms. 

Thanks!

**Comment by xclud** [comment]
@micdoug thanks for reporting. I will investigate the issue let you know.

**Comment by xclud** [comment]
@micdoug this problem is now fixed in v0.3.1.

I am closing this issue as it's solved now. Please open a new issue anytime.
