### ISSUE TITLE
Please add some more documentation

### ISSUE THREAD

**Issue by escamoteur** [xclud/flutter_crop#61]
Hi,

your Cropping widget looks awesome and exactly what I need. Unfortunately I'm absolutely not clear on how I really have to use it.

* What is the `helper` good for?
* How is the intended workflow with this widget? 
* Do I have to handle gestures myself and use the controller accordingly to zoom / pan?
* If I want to cut a smaller area from my image, do I have to zoom in and pan so that the area that I want fills the whole Crop widget?

I really would be greateful for some pointers.

**Comment by xclud** [comment]
@escamoteur Thank you for the feedback. My intention is to provide a documentation with version `1.0.0`. Meanwhile, is the example project helpful? Do you have any questions?

**Comment by escamoteur** [comment]
I tried to make sense of the example project but didn't fully understand it. See my questions above. If you could give a short explanation it would be great

**Comment by xclud** [comment]
- `helper` is used to display something on screen, but not on the final cropped image. You can use this for grids, golden ratios, focus indicators and so on.
- This is a very general question. Please be specific.
- The gestures are handled automatically. The widget is interactive. To disable the gestures set `interactive: false` in Crop constructor.
- The end user can use the gestures to zoom in [and out]. The latest version supports rotation with gestures as well.

**Comment by escamoteur** [comment]
Ah, I now know why I did not understand it. I only tried it yesterday on Desktop where zooming with the mouse wheel isn't supported yet, so I also could not really pan.

In now ttried the Web demo on my phone and it made sense. 
Will try to add a listener for the mouse wheel and try again.

**Comment by xclud** [comment]
This is a great feekback. Mouse gestures must be added to the package.

**Comment by escamoteur** [comment]
I managed it https://youtu.be/7WBgibXb_oQ

**Comment by xclud** [comment]
I am happy you did it on `20:45` xD And thank you for demoing this package. I appreciate if you refactor parts of your codes and contribute. You are a good teacher BTW.

**Comment by escamoteur** [comment]
Thanks, I'll try but I have so much to do with my own packages at the moment
