### ISSUE TITLE
Move outside the aspect ratio [BUG]

### ISSUE THREAD

**Issue by Sipioteo** [xclud/flutter_crop#63]
I found this strange bug. I set the aspect ratio and if the image don't has the same aspect ratio i can't move the selection pane outside the first aspect ratio. It's hard to explain, i attach a gif.

[https://media.giphy.com/media/QqcVylqMP1Ifw18DRt/source.mov](https://media.giphy.com/media/QqcVylqMP1Ifw18DRt/source.mov)

Hope you can fix this.

**Comment by xclud** [comment]
Hi @Sipioteo. This is a dup of #27 and I am already working on this.

I close this issue. Please follow the other issue and feel free to open a new issue any time.
