### ISSUE TITLE
Disable rotation?

### ISSUE THREAD

**Issue by Mayb3Nots** [xclud/flutter_crop#64]
Is there a way to disable rotation to only accept scale input? I wanna zoom in without touching the rotation of the image

**Comment by xclud** [comment]
@Mayb3Nots Currently not possible. This is a great feature to have. Adding this issue to project v1.

**Comment by xclud** [comment]
@Mayb3Nots Meanwhite, you can set `interactive` to `false` and wrap Crop widget in a GestureDetector and scale using `CropController.scale`.

**Comment by Mayb3Nots** [comment]
@xclud I have added a PR to add this feature. #66

**Comment by Keatr0n** [comment]
I had this problem too, I just did this
`
onChanged: (data) {
   if (data.rotation != 0) {
      croppedController.rotation = 0;
   }
},
`

**Comment by xclud** [comment]
I am closing this PR as @Keatr0n's solutions seems OK. Thank you.

**Comment by paricleu** [comment]
I think this feature warrants its own flag and not some workaround in a callback that's not meant for disabling features.
Is there a reason the PR couldn't be merged into the plugin? If there are things that need fixing I would be willing to have a go at it.

**Comment by Mayb3Nots** [comment]
> I think this feature warrants its own flag and not some workaround in a callback that's not meant for disabling features.
> Is there a reason the PR couldn't be merged into the plugin? If there are things that need fixing I would be willing to have a go at it.

I agree with everything you mentioned
