### ISSUE TITLE
Crop view doesnt let me crop at the edges with certain aspect ratio

### ISSUE THREAD

**Issue by Mayb3Nots** [xclud/flutter_crop#65]
I cant seem to get the plugin to work. 
Here is my code
``` dart
class CustomImageEditor extends StatefulWidget {
  final File data;

  CustomImageEditor({
    Key? key,
    required this.data,
  }) : super(key: key);

  @override
  _CustomImageEditorState createState() => _CustomImageEditorState();
}

class _CustomImageEditorState extends State<CustomImageEditor> {
  
  late CropController _controller;

  @override
  void initState() {
    _controller = CropController(aspectRatio: 1);

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Crop(
      onChanged: (decomposition) {},
      controller: _controller,
      child: Image.file(
        widget.data,
        fit: BoxFit.cover,
      ),
      helper: IgnorePointer(
        child: DecoratedBox(
          decoration: BoxDecoration(border: Border.all(color: Colors.white)),
        ),
      ),
    );
  }
}
```
This is wrapped in an aspect ratio of 1 under a column.

Here is the [video ](https://sjkcyuhuaedu-my.sharepoint.com/:v:/g/personal/samuelong_sjkcyuhua_edu_my/EdNYSEzUDltClalh6ESR-lQBfLsTeRLGQW2_bUhYBkdDeQ?e=7DUf3F)to show the issue

**Comment by Mayb3Nots** [comment]
Here is another example from the example app. 
[Video](https://sjkcyuhuaedu-my.sharepoint.com/:v:/g/personal/samuelong_sjkcyuhua_edu_my/EdI4oew_er5Em7H0zelSO3sBW9cPmZdfedKg6BLYGtT2gw?e=jxiMCG)

It seems that it only happens for certain ratio like 1:1

**Comment by xclud** [comment]
@Mayb3Nots This is a dup of #27. I close this issue. Please feel free to open a new issue.
