### ISSUE TITLE
Can not change crop size

### ISSUE THREAD

**Issue by lewooz** [xclud/flutter_crop#7]
Hi, first of all thanks for all the effort you put in to create such a great library that makes cropping image in flutter web possible. In our project we want to use this library but we need to change the size of the cropper and the cropper shouldn't extend image's size (to avoid getting blank area in the cropped image).

We want pretty much the same thing as you can see in this link: https://alyle.io/components/image-cropper.

Thanks!

**Comment by xclud** [comment]
Hi @lewooz,

> we need to change the size of the cropper

Do you mean the aspect ratio? If yes, this feature already exist in the package (I need to update the demo app in Google Play Store, but /example folder should be enough to get started for you).

> the cropper shouldn't extend image's size (to avoid getting blank area in the cropped image)

This is the out-of-the-box behavior of my package.

**Comment by lewooz** [comment]
Thanks for the response. After playing a bit more with it, I managed to solve the issue with using aspect ratio and setting height and width to the container wrapping the crop widget.

**Comment by xclud** [comment]
This is great. I am closing this issue but please feel free to open a new one anytime.
