### ISSUE TITLE
How to chagne offset of image?

### ISSUE THREAD

**Issue by sonlam103** [xclud/flutter_crop#72]
I tried moving the photo inside the square, it always returns to the original position (Offset(0, 0)). Is it possible to set the edge of the image to be equal to the edge of the square when the image moves out of the square?

**Comment by xclud** [comment]
It always makes the canvas fill with image and does not allow any blank space left. Do you expect another behavior?

I didn't understand the behavior you are trying to achieve.

**Comment by aduval** [comment]
Hi,

I have a similar issue with a rectangle shape. The crop widget displays figure A, I move it to get figure B, but it comes back to figure A. I expect it to allow B and crop it that way. Thanks for your help !

<img width="355" alt="crop" src="https://user-images.githubusercontent.com/3316055/142452291-ba4add82-6abc-4f76-9cf4-1b476ef40ccf.png">

**Comment by xclud** [comment]
@aduval This is a dup of #27. @margorski is working on a fix in #71.

**Comment by sonlam103** [comment]
@xclud Thanks for reply!
