### ISSUE TITLE
Preview is not loading on pub.dev

### ISSUE THREAD

**Issue by nilsreichardt** [xclud/flutter_crop#73]
The preview image is not loading on [pub.dev ](https://pub.dev/packages/crop):

![image](https://user-images.githubusercontent.com/24459435/147614862-5eea08e3-c756-4e0b-8229-08a6985bbe3c.png)

I tested with Chrome & Safari.

In the GitHub `README.md` it's working.

**Comment by xclud** [comment]
Hi. Thank you for reporting. This is fixed now. I am closing this issue but please feel free to open a new issue any time.
