### ISSUE TITLE
Compression option

### ISSUE THREAD

**Issue by jbryanh** [xclud/flutter_crop#74]
Feature request to include an imageQuality.  I was looking to use this along with image_picker on Flutter Web.  The output from crop explodes the file size, and I've struggled to efficiently solve getting the file back to an efficient size.

**Comment by xclud** [comment]
Meantime you can use https://pub.dev/packages/image to re-compress the output file.

**Comment by jbryanh** [comment]
thanks.  Wound up using [crop_your_image](https://pub.dev/packages/crop_your_image) simple Uint8List in and out wins the day on Flutter Web.  Thank you though for a great package @xclud.  I appreciate the ingenuity and hard work.
