### ISSUE TITLE
[feature request] include background

### ISSUE THREAD

**Issue by megz15** [xclud/flutter_crop#75]
Hello, first of all, wonderful package!
Would it be possible to add inclusion of background colour in the cropped image, like https://github.com/icapps/flutter-custom-image-crop does?
I looked at the code but couldn't figure out how. I'll fork later and play around with the code to accomplish it
Thank you :)

**Comment by xclud** [comment]
Hi,
There are `background` and `overlay` fields in the constructor. `overlay` will be visible in the output as a foreground.

**Comment by megz15** [comment]
Hey, thanks for your response. I was able to accomplish the result I needed in the end, thank you :)
