### ISSUE TITLE
PersistedOffset: is in an unexpected state error

### ISSUE THREAD

**Issue by lewooz** [xclud/flutter_crop#8]
Hi again,

I am always getting the error below when I try to crop an image : 

The following PersistedSurfaceException was thrown during a scheduler callback:

PersistedOffset: is in an unexpected state.

Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released

But was: PersistedSurfaceState.created

I have made some research on the internet but couldn't find a way to solve this error. I can share my code if needed.

Thanks.

**Comment by xclud** [comment]
Hi,
Which platform are you building? If Web, its a bug in flutter engine which i am aware of.

Flutter for web is not ready for production builds yet and i am patient about reporting the bug. I hope this package will eventually work on web once flutter for web is officially released.

**Comment by lewooz** [comment]
Yes, I am building for web. Then we have no other option but to wait for an update to solve this issue in flutter engine I guess.

Thanks for the information.

**Comment by xclud** [comment]
Meanwhile you may test your project on an android device or an emulator.

I am closing this issue as we have to wait.

**Comment by dhianabli** [comment]
this is an issue that I also stumble upon sometimes with flutter web and I think it is related to the rendering engine. Hope that will be fixed soon

**Comment by NicolasDionB** [comment]
@xclud Any update on this? I see the issue is closed but there's no link to follow whatsoever.

**Comment by xclud** [comment]
@NicolasDionB I am tracking the flutter milestones and i will let you know once i get `crop` package working on the web.

**Comment by DomingoMG** [comment]
I have the same problem.

**Comment by xclud** [comment]
https://github.com/flutter/flutter/issues/42767
