### ISSUE TITLE
Translation adjustment stuck inside box same shape as crop aspect ratio

### ISSUE THREAD

**Issue by lukehutch** [xclud/flutter_crop#83]
If I have a photo with a 16:9 aspect ratio, and then I create a `CropController` with `aspectRatio: 1`, then the selectable area for the crop is a 1:1 aspect ratio square in the middle of the image (call this the "valid area"). That means that I can zoom in, and manually drag the translation position of the square crop region anywhere within the valid area, but if I try to drag to the left or right of the valid area, the translation animates back to an area within the valid area. This means that the portion of the image to the left and right of the valid area cannot be included in the crop region.

**Comment by lukehutch** [comment]
I think the problem is here, in `crop.dart`:

```dart
    final ctl = canvas.topLeft;
    final ctr = canvas.topRight;
    final cbr = canvas.bottomRight;
    final cbl = canvas.bottomLeft;
```

I think these should be set to the corners of the image, not the corners of the canvas.

**Comment by xclud** [comment]
Hi. This is a dup of #27.

**Comment by lukehutch** [comment]
Sorry I didn't see the other bug. Thanks.
