### ISSUE TITLE
The image is always re-centered when dragging (even if boundaries are not reached)

### ISSUE THREAD

**Issue by ramtinq** [xclud/flutter_crop#85]
If for example we have an image with `controller.aspectRatio = 16 / 9` and an image with smaller aspect ratio, like `9 / 16`, and we drag up and down, the image is re-centered. This should not happen except when we have dragged more than the boundaries, and then the image should move to the position just before exceeding the boundaries.

**Comment by xclud** [comment]
This is a dup of #27.
