### ISSUE TITLE
Screenshot in `README.md` is not loading 

### ISSUE THREAD

**Issue by nilsreichardt** [xclud/flutter_crop#90]
<img width="972" alt="image" src="https://github.com/xclud/flutter_crop/assets/24459435/d75771f9-97bc-4215-8f83-8a5fa4a9740b">

**Comment by xclud** [comment]
Hi. Thanks for notifying. The screenshot is removed in favor of the web demo.

I removed it from README.md.

**Comment by nilsreichardt** [comment]
Cool, thanks. Closing the ticket since it's solved 👍
